export {default as Home} from './Home'
export {default as Account} from './Account'
export {default as Music} from './Music'
export {default as Search} from './Search'
export {default as Details} from './Details'