export default {
    playlist1: require("../assets/images/playlist1.png"),
    playlist2: require("../assets/images/playlist2.png"),
    playlist3: require("../assets/images/playlist3.png"),
    playlist4: require("../assets/images/playlist4.png"),
    playlist5: require("../assets/images/playlist5.png"),
    playlist6: require("../assets/images/playlist6.png"),
    playlist7: require("../assets/images/playlist7.png"),
    artist1: require("../assets/images/artist1.png"),
    artist2: require("../assets/images/artist2.png"),
    artist3: require("../assets/images/artist3.png"),
    artist4: require("../assets/images/artist4.png"),
    search1: require("../assets/images/search1.png"),
    search2: require("../assets/images/search2.png"),
    search3: require("../assets/images/search3.png"),
    search4: require("../assets/images/search4.png"),
    search5: require("../assets/images/search5.png"),
    search6: require("../assets/images/search6.png"),
    search7: require("../assets/images/search7.png"),
    search8: require("../assets/images/search8.png"),
    search9: require("../assets/images/search9.png"),
    adv_bg: require("../assets/images/adv_bg.png"),
    avatar: require("../assets/images/avatar.png"),
    bg_details: require("../assets/images/bg_details.png"),
    linear_bg: require("../assets/images/linear_bg.png"),
}